// <auto-generated />
using System;
using FreshVeggies.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshVeggies.Api.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/avocado.png",
                            Name = "Avocado",
                            Price = 5.00m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/beet.png",
                            Name = "Beet",
                            Price = 10.00m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/bell_pepper.png",
                            Name = "Bell Pepper",
                            Price = 10.00m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/broccoli.png",
                            Name = "Broccoli",
                            Price = 9.99m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/cabbage.png",
                            Name = "Cabbage",
                            Price = 15.50m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/capsicum.png",
                            Name = "Capsicum",
                            Price = 21.80m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/carrot.png",
                            Name = "Carrot",
                            Price = 10.80m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/cauliflower.png",
                            Name = "Cauliflower",
                            Price = 20.50m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/coriander.png",
                            Name = "Coriander",
                            Price = 10.70m,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/corn.png",
                            Name = "Corn",
                            Price = 15.00m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/cucumber.png",
                            Name = "Cucumber",
                            Price = 10.90m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/eggplant.png",
                            Name = "Eggplant",
                            Price = 15.75m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/farmer.png",
                            Name = "Farmer",
                            Price = 15.00m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/ginger.png",
                            Name = "Ginger",
                            Price = 22.20m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/green_beans.png",
                            Name = "Green Beans",
                            Price = 31.60m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/ladyfinger.png",
                            Name = "Ladyfinger",
                            Price = 21.10m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/lettuce.png",
                            Name = "Lettuce",
                            Price = 10.30m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/mushroom.png",
                            Name = "Mushroom",
                            Price = 12.80m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/onion.png",
                            Name = "Onion",
                            Price = 20.60m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/pea.png",
                            Name = "Pea",
                            Price = 25.40m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/potato.png",
                            Name = "Potato",
                            Price = 50.50m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/pumpkin.png",
                            Name = "Pumpkin",
                            Price = 23.00m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/radish.png",
                            Name = "Radish",
                            Price = 20.85m,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/red_chili.png",
                            Name = "Red Chili",
                            Price = 11.50m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/spinach.png",
                            Name = "Spinach",
                            Price = 15.20m,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/tomato.png",
                            Name = "Tomato",
                            Price = 20.95m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/turnip.png",
                            Name = "Turnip",
                            Price = 10.75m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/vegetables.png",
                            Name = "Vegetables",
                            Price = 14.00m,
                            Unit = "each"
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://raw.githubusercontent.com/Abhayprince/Images-Icons/refs/heads/main/Vegetables/yellow_capsicum.png",
                            Name = "Yellow Capsicum",
                            Price = 11.80m,
                            Unit = "each"
                        });
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cellphone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.Address", b =>
                {
                    b.HasOne("FreshVeggies.Api.Domain.Models.User", "User")
                        .WithMany("UserAddress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.Order", b =>
                {
                    b.HasOne("FreshVeggies.Api.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("FreshVeggies.Api.Domain.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FreshVeggies.Api.Domain.Models.User", b =>
                {
                    b.Navigation("UserAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
